// <auto-generated />
using Course_Registration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Course_Registration.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Course_Registration.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 100,
                            CourseName = "Introduction to IT",
                            CourseNumber = 1,
                            Description = "This course develops a basic understanding and competence in Information and Communications Technology. Students will gain awareness of hardware, software, and fundamental programming principles, along with hands on experience in problem solving using pseudo code and flowcharts. Assignments are designed to provide students with practical experience in solving problems in a structured manner."
                        },
                        new
                        {
                            CourseId = 101,
                            CourseName = "Structured Programming in Java",
                            CourseNumber = 2,
                            Description = "This course is intended for students with no prior knowledge in programming. It provides an introduction to the development of solutions in Java using procedural techniques.It explores standard Java programming structures, including constants, variables, assignment statements, conditional logic, looping, functions, and user input/output methods to develop solutions in Java."
                        },
                        new
                        {
                            CourseId = 102,
                            CourseName = "Object Oriented Programming",
                            CourseNumber = 3,
                            Description = "This course introduces students to the basic concepts of object-oriented programming in Java, focusing on the definition and use of classes along with the fundamentals of object-oriented design and programming techniques.Other topics include Unified Modelling Language(UML), arrays, analysis of algorithms, basic searching and sorting techniques, and memory management."
                        },
                        new
                        {
                            CourseId = 103,
                            CourseName = "Inheritance and Polymorphism",
                            CourseNumber = 4,
                            Description = "A continuation of Object-Oriented Programming in Java, this course provides a deeper examination of object-oriented programming through Inheritance and Polymorphism. Issues related to program design, modularization, and code reuse will be emphasized."
                        },
                        new
                        {
                            CourseId = 104,
                            CourseName = "Relational Databases and SQL",
                            CourseNumber = 5,
                            Description = "This course covers the fundamentals of relational database systems.Topics to be examined include database requirements, Entity Relationship modelling, database design, and Structured Query Language(SQL). Emphasis will be placed on data retrieval and manipulation techniques required in web applications."
                        },
                        new
                        {
                            CourseId = 105,
                            CourseName = "Web Development Basics",
                            CourseNumber = 6,
                            Description = "This fundamental course in web development introduces students to HTML, CSS, and JavaScript.It employs a problem-based approach which requires the student to design and create a website of ever-increasing complexity as the course progresses."
                        },
                        new
                        {
                            CourseId = 106,
                            CourseName = "Business Communications",
                            CourseNumber = 7,
                            Description = "This course provides students with the knowledge and tools to communicate effectively and professionally in the workplace.Students will be introduced to essential skills in writing, speaking, formal presentations and the use of technology to enhance workplace communication."
                        },
                        new
                        {
                            CourseId = 107,
                            CourseName = "Career Preparation",
                            CourseNumber = 8,
                            Description = "In this course, students will be introduced to strategies for a successful job search, interview and career management. In the current competitive job search environment, it is essential for students to understand who they are, the skills they offer, what to expect from professional employment, and what employers expect of them."
                        },
                        new
                        {
                            CourseId = 108,
                            CourseName = "Version Control with Github",
                            CourseNumber = 9,
                            Description = "The Version Control with Git and Github course provides students with a comprehensive, hands-on foundation of the Git version control system.Effective use of version control is an important and useful skill for any developer working on multi-developer projects."
                        },
                        new
                        {
                            CourseId = 109,
                            CourseName = "ASP.NET Core",
                            CourseNumber = 12,
                            Description = "This course is intended for programmers with experience in C# who are interested in developing, and further enhancing, the skills necessary to build dynamic web applications running in the Cloud. The focus of the course is on creating applications with ASP.NET Core in order to build full stack Single Page Applications and REST APIs.This course prepares students for the Certified Tester"
                        },
                        new
                        {
                            CourseId = 110,
                            CourseName = "Front End Frameworks",
                            CourseNumber = 13,
                            Description = "Students will learn to develop dynamic Single Page Web Applications using three of today’s most popular front-end frameworks: Angular, React, and Vue.Through a series of graduated assignments, students will develop an application called The Everyday Market App in each of the three frameworks.The Everyday Market App contains all the components of a standard shopping cart app"
                        });
                });

            modelBuilder.Entity("Course_Registration.Models.CourseStudent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseIdjq")
                        .HasColumnType("int");

                    b.Property<string>("Emailjq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNamejq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNamejq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentIdjq")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CourseIdjq = 100,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 2,
                            CourseIdjq = 100,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 3,
                            CourseIdjq = 100,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 4,
                            CourseIdjq = 100,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 5,
                            CourseIdjq = 100,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 6,
                            CourseIdjq = 100,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 7,
                            CourseIdjq = 100,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 8,
                            CourseIdjq = 100,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 9,
                            CourseIdjq = 100,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 10,
                            CourseIdjq = 100,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 11,
                            CourseIdjq = 100,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 12,
                            CourseIdjq = 101,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 13,
                            CourseIdjq = 101,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 14,
                            CourseIdjq = 101,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 15,
                            CourseIdjq = 101,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 16,
                            CourseIdjq = 101,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 17,
                            CourseIdjq = 101,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 18,
                            CourseIdjq = 101,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 19,
                            CourseIdjq = 101,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 20,
                            CourseIdjq = 101,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 21,
                            CourseIdjq = 102,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 22,
                            CourseIdjq = 102,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 23,
                            CourseIdjq = 102,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 24,
                            CourseIdjq = 102,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 25,
                            CourseIdjq = 102,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 26,
                            CourseIdjq = 102,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 27,
                            CourseIdjq = 102,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 28,
                            CourseIdjq = 102,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 29,
                            CourseIdjq = 102,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 30,
                            CourseIdjq = 103,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 31,
                            CourseIdjq = 103,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 32,
                            CourseIdjq = 103,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 33,
                            CourseIdjq = 103,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 34,
                            CourseIdjq = 103,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 35,
                            CourseIdjq = 103,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 36,
                            CourseIdjq = 104,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 37,
                            CourseIdjq = 104,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 38,
                            CourseIdjq = 104,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 39,
                            CourseIdjq = 104,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 40,
                            CourseIdjq = 104,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 41,
                            CourseIdjq = 104,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 42,
                            CourseIdjq = 105,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 43,
                            CourseIdjq = 105,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 44,
                            CourseIdjq = 105,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 45,
                            CourseIdjq = 105,
                            Emailjq = "info@mysite.ca",
                            FirstNamejq = "Sean 8",
                            LastNamejq = "Roberts8",
                            StudentIdjq = 207
                        },
                        new
                        {
                            id = 46,
                            CourseIdjq = 105,
                            Emailjq = "info@newssite.ca",
                            FirstNamejq = "Sean 9",
                            LastNamejq = "Roberts9",
                            StudentIdjq = 208
                        },
                        new
                        {
                            id = 47,
                            CourseIdjq = 105,
                            Emailjq = "info@design.ca",
                            FirstNamejq = "Sean 10",
                            LastNamejq = "Roberts10",
                            StudentIdjq = 209
                        },
                        new
                        {
                            id = 48,
                            CourseIdjq = 106,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 49,
                            CourseIdjq = 106,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 50,
                            CourseIdjq = 106,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 51,
                            CourseIdjq = 106,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 52,
                            CourseIdjq = 106,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 53,
                            CourseIdjq = 106,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 54,
                            CourseIdjq = 106,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 55,
                            CourseIdjq = 107,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 56,
                            CourseIdjq = 107,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 57,
                            CourseIdjq = 107,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 58,
                            CourseIdjq = 107,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 59,
                            CourseIdjq = 107,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 60,
                            CourseIdjq = 107,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 61,
                            CourseIdjq = 107,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 62,
                            CourseIdjq = 108,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 63,
                            CourseIdjq = 108,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 64,
                            CourseIdjq = 108,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 65,
                            CourseIdjq = 108,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 66,
                            CourseIdjq = 108,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 67,
                            CourseIdjq = 108,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 68,
                            CourseIdjq = 108,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 69,
                            CourseIdjq = 109,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 70,
                            CourseIdjq = 109,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 71,
                            CourseIdjq = 109,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 72,
                            CourseIdjq = 109,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 73,
                            CourseIdjq = 109,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 74,
                            CourseIdjq = 109,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 75,
                            CourseIdjq = 109,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        },
                        new
                        {
                            id = 76,
                            CourseIdjq = 110,
                            Emailjq = "info@seanroberts.ca",
                            FirstNamejq = "Sean 1",
                            LastNamejq = "Roberts1",
                            StudentIdjq = 200
                        },
                        new
                        {
                            id = 77,
                            CourseIdjq = 110,
                            Emailjq = "info@google.ca",
                            FirstNamejq = "Sean 2",
                            LastNamejq = "Roberts2",
                            StudentIdjq = 201
                        },
                        new
                        {
                            id = 78,
                            CourseIdjq = 110,
                            Emailjq = "info@yahoo.ca",
                            FirstNamejq = "Sean 3",
                            LastNamejq = "Roberts3",
                            StudentIdjq = 202
                        },
                        new
                        {
                            id = 79,
                            CourseIdjq = 110,
                            Emailjq = "info@facebook.ca",
                            FirstNamejq = "Sean 4",
                            LastNamejq = "Roberts4",
                            StudentIdjq = 203
                        },
                        new
                        {
                            id = 80,
                            CourseIdjq = 110,
                            Emailjq = "info@apple.ca",
                            FirstNamejq = "Sean 5",
                            LastNamejq = "Roberts5",
                            StudentIdjq = 204
                        },
                        new
                        {
                            id = 81,
                            CourseIdjq = 110,
                            Emailjq = "info@bing.ca",
                            FirstNamejq = "Sean 6",
                            LastNamejq = "Roberts6",
                            StudentIdjq = 205
                        },
                        new
                        {
                            id = 82,
                            CourseIdjq = 110,
                            Emailjq = "info@yelp.ca",
                            FirstNamejq = "Sean 7",
                            LastNamejq = "Roberts7",
                            StudentIdjq = 206
                        });
                });

            modelBuilder.Entity("Course_Registration.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            CourseId = 100,
                            Email = "david1@yahoo.com",
                            FirstName = "Teacher 1",
                            LastName = "Jones 1"
                        },
                        new
                        {
                            Id = 10001,
                            CourseId = 101,
                            Email = "david2@yahoo.com",
                            FirstName = "Teacher 2",
                            LastName = "Jones 2"
                        },
                        new
                        {
                            Id = 10002,
                            CourseId = 102,
                            Email = "david3@yahoo.com",
                            FirstName = "Teacher 3",
                            LastName = "Jones 3"
                        },
                        new
                        {
                            Id = 10003,
                            CourseId = 103,
                            Email = "david4@yahoo.com",
                            FirstName = "Teacher 4",
                            LastName = "Jones 4"
                        },
                        new
                        {
                            Id = 10004,
                            CourseId = 104,
                            Email = "david5@yahoo.com",
                            FirstName = "Teacher 5",
                            LastName = "Jones 5"
                        },
                        new
                        {
                            Id = 10005,
                            CourseId = 105,
                            Email = "david6@yahoo.com",
                            FirstName = "Teacher 6",
                            LastName = "Jones 6"
                        },
                        new
                        {
                            Id = 10006,
                            CourseId = 106,
                            Email = "david7@yahoo.com",
                            FirstName = "Teacher 7",
                            LastName = "Jones 7"
                        },
                        new
                        {
                            Id = 10007,
                            CourseId = 107,
                            Email = "david8@yahoo.com",
                            FirstName = "Teacher 8",
                            LastName = "Jones 8"
                        },
                        new
                        {
                            Id = 10008,
                            CourseId = 108,
                            Email = "david9@yahoo.com",
                            FirstName = "Teacher 9",
                            LastName = "Jones 9"
                        },
                        new
                        {
                            Id = 10009,
                            CourseId = 109,
                            Email = "david10@yahoo.com",
                            FirstName = "Teacher 10",
                            LastName = "Jones 10"
                        },
                        new
                        {
                            Id = 10010,
                            CourseId = 110,
                            Email = "david11@yahoo.com",
                            FirstName = "Teacher 11",
                            LastName = "Jones 11"
                        });
                });

            modelBuilder.Entity("Course_Registration.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 200,
                            CourseId = 0,
                            Email = "info@seanroberts.ca",
                            FirstName = "Sean 1",
                            LastName = "Roberts1",
                            PhoneNumber = "204-899-1142"
                        },
                        new
                        {
                            StudentId = 201,
                            CourseId = 0,
                            Email = "info@google.ca",
                            FirstName = "Sean 2",
                            LastName = "Roberts2",
                            PhoneNumber = "204-999-2142"
                        },
                        new
                        {
                            StudentId = 202,
                            CourseId = 0,
                            Email = "info@yahoo.ca",
                            FirstName = "Sean 3",
                            LastName = "Roberts3",
                            PhoneNumber = "204-301-3142"
                        },
                        new
                        {
                            StudentId = 203,
                            CourseId = 0,
                            Email = "info@facebook.ca",
                            FirstName = "Sean 4",
                            LastName = "Roberts4",
                            PhoneNumber = "204-733-4142"
                        },
                        new
                        {
                            StudentId = 204,
                            CourseId = 0,
                            Email = "info@apple.ca",
                            FirstName = "Sean 5",
                            LastName = "Roberts5",
                            PhoneNumber = "204-541-5142"
                        },
                        new
                        {
                            StudentId = 205,
                            CourseId = 0,
                            Email = "info@bing.ca",
                            FirstName = "Sean 6",
                            LastName = "Roberts6",
                            PhoneNumber = "204-598-6142"
                        },
                        new
                        {
                            StudentId = 206,
                            CourseId = 0,
                            Email = "info@yelp.ca",
                            FirstName = "Sean 7",
                            LastName = "Roberts7",
                            PhoneNumber = "204-321-7142"
                        },
                        new
                        {
                            StudentId = 207,
                            CourseId = 0,
                            Email = "info@mysite.ca",
                            FirstName = "Sean 8",
                            LastName = "Roberts8",
                            PhoneNumber = "204-852-8142"
                        },
                        new
                        {
                            StudentId = 208,
                            CourseId = 0,
                            Email = "info@newssite.ca",
                            FirstName = "Sean 9",
                            LastName = "Roberts9",
                            PhoneNumber = "204-789-9142"
                        },
                        new
                        {
                            StudentId = 209,
                            CourseId = 0,
                            Email = "info@design.ca",
                            FirstName = "Sean 10",
                            LastName = "Roberts10",
                            PhoneNumber = "897-899-3142"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
